-- Virtual Warehouse Creation
CREATE OR REPLACE WAREHOUSE ECOMMERCE_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

-- Database Creation
CREATE OR REPLACE DATABASE ECOMMERCE_DB;

-- Schema Creation
USE DATABASE ECOMMERCE_DB;
CREATE OR REPLACE SCHEMA ECOMMERCE_SCHEMA;
USE SCHEMA ECOMMERCE_SCHEMA;

-- Internal Stage to support data loading
CREATE OR REPLACE STAGE ECOMMERCE_STAGE;

-- Customer Dimension Table Creation
CREATE OR REPLACE TABLE DIM_CUSTOMERS (
    CUSTOMER_ID STRING,
    CUSTOMER_UNIQUE_ID STRING,
    CUSTOMER_ZIP_CODE_PREFIX INTEGER,
    CUSTOMER_CITY STRING,
    CUSTOMER_STATE STRING
);

-- Product Dimension Table Creation
CREATE OR REPLACE TABLE DIM_PRODUCTS (
    PRODUCT_ID STRING,
    PRODUCT_CATEGORY_NAME STRING,
    PRODUCT_NAME_LENGTH INTEGER,
    PRODUCT_DESCRIPTION_LENGTH INTEGER,
    PRODUCT_PHOTOS_QTY INTEGER,
    PRODUCT_WEIGHT_G INTEGER,
    PRODUCT_LENGTH_CM INTEGER,
    PRODUCT_HEIGHT_CM INTEGER,
    PRODUCT_WIDTH_CM INTEGER
);

-- Seller Dimension Table Creation
CREATE OR REPLACE TABLE DIM_SELLERS (
    SELLER_ID STRING,
    SELLER_ZIP_CODE_PREFIX INTEGER,
    SELLER_CITY STRING,
    SELLER_STATE STRING
);

-- Date Dimension Table Creation
CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID INTEGER,
    FULL_DATE DATE,
    DAY INTEGER,
    MONTH INTEGER,
    QUARTER INTEGER,
    YEAR INTEGER,
    WEEKDAY STRING
);

-- Orders Fact Table Creation
CREATE OR REPLACE TABLE FACT_ORDERS (
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    ORDER_STATUS STRING,
    ORDER_PURCHASE_TIMESTAMP TIMESTAMP,
    ORDER_APPROVED_AT TIMESTAMP,
    ORDER_DELIVERED_CARRIER_DATE TIMESTAMP,
    ORDER_DELIVERED_CUSTOMER_DATE TIMESTAMP,
    ORDER_ESTIMATED_DELIVERY_DATE TIMESTAMP
);

-- Order Items Fact Table Creation
CREATE OR REPLACE TABLE FACT_ORDER_ITEMS (
    ORDER_ID STRING,
    ORDER_ITEM_ID INTEGER,
    PRODUCT_ID STRING,
    SELLER_ID STRING,
    SHIPPING_LIMIT_DATE TIMESTAMP,
    PRICE FLOAT,
    FREIGHT_VALUE FLOAT
);

-- Payments Fact Table Creation
CREATE OR REPLACE TABLE FACT_PAYMENTS (
    ORDER_ID STRING,
    PAYMENT_SEQUENTIAL INTEGER,
    PAYMENT_TYPE STRING,
    PAYMENT_INSTALLMENTS INTEGER,
    PAYMENT_VALUE FLOAT
);

-- Reviews Fact Table Creation
CREATE OR REPLACE TABLE FACT_REVIEWS (
    REVIEW_ID STRING,
    ORDER_ID STRING,
    REVIEW_SCORE INTEGER,
    REVIEW_COMMENT_TITLE STRING,
    REVIEW_COMMENT_MESSAGE STRING,
    REVIEW_CREATION_DATE DATE,
    REVIEW_ANSWER_TIMESTAMP TIMESTAMP
);
