-- =====================================================================
--          MILESTONE 3: SNOWFLAKE ANALYTICAL OBJECTS SETUP
-- =====================================================================

USE DATABASE ECOMMERCE_DB;
USE SCHEMA ECOMMERCE_SCHEMA;

-- ==========================================
-- 1. ANALYTICAL VIEWS FOR REPORTING
-- ==========================================

-- Customer Analytics View
CREATE OR REPLACE VIEW CUSTOMER_ANALYTICS_VIEW AS
SELECT
    c.CUSTOMER_UNIQUE_ID,
    c.CUSTOMER_CITY,
    c.CUSTOMER_STATE,
    COUNT(DISTINCT o.ORDER_ID) AS TOTAL_ORDERS,
    COALESCE(SUM(p.PAYMENT_VALUE), 0) AS TOTAL_SPENT,
    COALESCE(AVG(r.REVIEW_SCORE), 0) AS AVG_REVIEW_SCORE
FROM DIM_CUSTOMERS c
LEFT JOIN FACT_ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
LEFT JOIN FACT_PAYMENTS p ON o.ORDER_ID = p.ORDER_ID
LEFT JOIN FACT_REVIEWS r ON o.ORDER_ID = r.ORDER_ID
GROUP BY c.CUSTOMER_UNIQUE_ID, c.CUSTOMER_CITY, c.CUSTOMER_STATE;

-- Revenue Analytics View
CREATE OR REPLACE VIEW REVENUE_ANALYTICS_VIEW AS
SELECT
    d.YEAR,
    d.MONTH,
    d.QUARTER,
    o.ORDER_STATUS,
    c.CUSTOMER_STATE,
    COUNT(DISTINCT o.ORDER_ID) AS TOTAL_ORDERS,
    COALESCE(SUM(p.PAYMENT_VALUE), 0) AS TOTAL_REVENUE,
    COALESCE(SUM(i.FREIGHT_VALUE), 0) AS TOTAL_SHIPPING
FROM FACT_ORDERS o
JOIN DIM_DATE d ON TO_DATE(o.ORDER_PURCHASE_TIMESTAMP) = d.FULL_DATE
LEFT JOIN FACT_PAYMENTS p ON o.ORDER_ID = p.ORDER_ID
LEFT JOIN DIM_CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN FACT_ORDER_ITEMS i ON o.ORDER_ID = i.ORDER_ID
GROUP BY d.YEAR, d.MONTH, d.QUARTER, o.ORDER_STATUS, c.CUSTOMER_STATE;

-- Product Analytics View
CREATE OR REPLACE VIEW PRODUCT_ANALYTICS_VIEW AS
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_CATEGORY_NAME,
    COUNT(i.ORDER_ITEM_ID) AS TOTAL_UNITS_SOLD,
    COALESCE(SUM(i.PRICE), 0) AS TOTAL_REVENUE,
    COALESCE(SUM(i.FREIGHT_VALUE), 0) AS TOTAL_FREIGHT,
    COALESCE(AVG(i.PRICE), 0) AS AVG_PRICE
FROM DIM_PRODUCTS p
LEFT JOIN FACT_ORDER_ITEMS i ON p.PRODUCT_ID = i.PRODUCT_ID
GROUP BY p.PRODUCT_ID, p.PRODUCT_CATEGORY_NAME;

-- Seller Analytics View
CREATE OR REPLACE VIEW SELLER_ANALYTICS_VIEW AS
SELECT
    s.SELLER_ID,
    s.SELLER_CITY,
    s.SELLER_STATE,
    COUNT(DISTINCT i.ORDER_ID) AS TOTAL_ORDERS,
    COUNT(i.ORDER_ITEM_ID) AS TOTAL_ITEMS_SOLD,
    COALESCE(SUM(i.PRICE), 0) AS TOTAL_REVENUE,
    COALESCE(SUM(i.FREIGHT_VALUE), 0) AS TOTAL_FREIGHT
FROM DIM_SELLERS s
LEFT JOIN FACT_ORDER_ITEMS i ON s.SELLER_ID = i.SELLER_ID
GROUP BY s.SELLER_ID, s.SELLER_CITY, s.SELLER_STATE;

-- Review Analytics View
CREATE OR REPLACE VIEW REVIEW_ANALYTICS_VIEW AS
SELECT
    r.REVIEW_ID,
    r.ORDER_ID,
    r.REVIEW_SCORE,
    r.REVIEW_COMMENT_TITLE,
    r.REVIEW_COMMENT_MESSAGE,
    r.REVIEW_CREATION_DATE,
    o.ORDER_STATUS,
    c.CUSTOMER_STATE
FROM FACT_REVIEWS r
LEFT JOIN FACT_ORDERS o ON r.ORDER_ID = o.ORDER_ID
LEFT JOIN DIM_CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID;


-- ==========================================
-- 2. REPORTING SUMMARY TABLES & STORED PROCEDURES
-- ==========================================

-- Daily Summary Table for fast KPI reads
CREATE OR REPLACE TABLE REPORT_DAILY_KPI (
    REPORT_DATE DATE PRIMARY KEY,
    TOTAL_REVENUE FLOAT,
    TOTAL_ORDERS INTEGER,
    TOTAL_CUSTOMERS INTEGER,
    AVG_REVIEW_SCORE FLOAT
);

-- Customer Lifetime Value (CLV) Summary Table
CREATE OR REPLACE TABLE CUSTOMER_CLV_SUMMARY (
    CUSTOMER_UNIQUE_ID STRING PRIMARY KEY,
    TOTAL_REVENUE FLOAT,
    TOTAL_ORDERS INTEGER,
    AVG_ORDER_VALUE FLOAT,
    LIFETIME_DAYS INTEGER,
    CLV_SCORE FLOAT
);

-- RFM Customer Segments Table
CREATE OR REPLACE TABLE CUSTOMER_RFM_SEGMENTS (
    CUSTOMER_UNIQUE_ID STRING PRIMARY KEY,
    RECENCY_DAYS INTEGER,
    FREQUENCY INTEGER,
    MONETARY FLOAT,
    R_SCORE INTEGER,
    F_SCORE INTEGER,
    M_SCORE INTEGER,
    RFM_SCORE STRING,
    SEGMENT STRING
);

-- Stored Procedure to recalculate daily KPIs
CREATE OR REPLACE PROCEDURE REFRESH_ANALYTICS_DATA()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    TRUNCATE TABLE REPORT_DAILY_KPI;
    
    INSERT INTO REPORT_DAILY_KPI (REPORT_DATE, TOTAL_REVENUE, TOTAL_ORDERS, TOTAL_CUSTOMERS, AVG_REVIEW_SCORE)
    SELECT
        TO_DATE(o.ORDER_PURCHASE_TIMESTAMP) AS REPORT_DATE,
        COALESCE(SUM(p.PAYMENT_VALUE), 0) AS TOTAL_REVENUE,
        COUNT(DISTINCT o.ORDER_ID) AS TOTAL_ORDERS,
        COUNT(DISTINCT o.CUSTOMER_ID) AS TOTAL_CUSTOMERS,
        COALESCE(AVG(r.REVIEW_SCORE), 0) AS AVG_REVIEW_SCORE
    FROM FACT_ORDERS o
    LEFT JOIN FACT_PAYMENTS p ON o.ORDER_ID = p.ORDER_ID
    LEFT JOIN FACT_REVIEWS r ON o.ORDER_ID = r.ORDER_ID
    GROUP BY REPORT_DATE;
    
    RETURN 'Analytics reporting summary table refreshed successfully!';
END;
$$;

-- Stored Procedure to calculate Customer Lifetime Value (CLV)
CREATE OR REPLACE PROCEDURE CALCULATE_CLV()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    TRUNCATE TABLE CUSTOMER_CLV_SUMMARY;
    
    INSERT INTO CUSTOMER_CLV_SUMMARY (CUSTOMER_UNIQUE_ID, TOTAL_REVENUE, TOTAL_ORDERS, AVG_ORDER_VALUE, LIFETIME_DAYS, CLV_SCORE)
    SELECT
        c.CUSTOMER_UNIQUE_ID,
        COALESCE(SUM(p.PAYMENT_VALUE), 0) AS TOTAL_REVENUE,
        COUNT(DISTINCT o.ORDER_ID) AS TOTAL_ORDERS,
        CASE WHEN COUNT(DISTINCT o.ORDER_ID) > 0 THEN COALESCE(SUM(p.PAYMENT_VALUE), 0) / COUNT(DISTINCT o.ORDER_ID) ELSE 0 END AS AVG_ORDER_VALUE,
        COALESCE(DATEDIFF(day, MIN(o.ORDER_PURCHASE_TIMESTAMP), MAX(o.ORDER_PURCHASE_TIMESTAMP)), 1) AS LIFETIME_DAYS,
        -- Projected CLV: Historical revenue scaled by purchase activity and a loyalty factor
        COALESCE(SUM(p.PAYMENT_VALUE), 0) * (1.0 + (COALESCE(DATEDIFF(day, MIN(o.ORDER_PURCHASE_TIMESTAMP), MAX(o.ORDER_PURCHASE_TIMESTAMP)), 1) / 365.0) * 0.1) AS CLV_SCORE
    FROM DIM_CUSTOMERS c
    JOIN FACT_ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
    LEFT JOIN FACT_PAYMENTS p ON o.ORDER_ID = p.ORDER_ID
    GROUP BY c.CUSTOMER_UNIQUE_ID;
    
    RETURN 'Customer Lifetime Value (CLV) calculation completed successfully!';
END;
$$;

-- Stored Procedure to refresh RFM Customer Segments
CREATE OR REPLACE PROCEDURE REFRESH_RFM_SEGMENTS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    TRUNCATE TABLE CUSTOMER_RFM_SEGMENTS;
    
    INSERT INTO CUSTOMER_RFM_SEGMENTS (
        CUSTOMER_UNIQUE_ID, RECENCY_DAYS, FREQUENCY, MONETARY, R_SCORE, F_SCORE, M_SCORE, RFM_SCORE, SEGMENT
    )
    WITH CustomerStats AS (
        SELECT
            c.CUSTOMER_UNIQUE_ID,
            -- Recency: Days since last order relative to the maximum date in database
            DATEDIFF(day, MAX(o.ORDER_PURCHASE_TIMESTAMP), (SELECT MAX(ORDER_PURCHASE_TIMESTAMP) FROM FACT_ORDERS)) AS RECENCY_DAYS,
            COUNT(DISTINCT o.ORDER_ID) AS FREQUENCY,
            COALESCE(SUM(p.PAYMENT_VALUE), 0) AS MONETARY
        FROM DIM_CUSTOMERS c
        JOIN FACT_ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
        LEFT JOIN FACT_PAYMENTS p ON o.ORDER_ID = p.ORDER_ID
        GROUP BY c.CUSTOMER_UNIQUE_ID
    ),
    RFMScores AS (
        SELECT
            CUSTOMER_UNIQUE_ID,
            RECENCY_DAYS,
            FREQUENCY,
            MONETARY,
            -- Recency: lower days -> higher score (5 is best)
            NTILE(5) OVER (ORDER BY RECENCY_DAYS DESC) AS R_SCORE,
            -- Frequency: higher frequency -> higher score. Scale using common frequency values.
            CASE WHEN FREQUENCY = 1 THEN 1 WHEN FREQUENCY = 2 THEN 3 ELSE 5 END AS F_SCORE,
            -- Monetary: higher spend -> higher score
            NTILE(5) OVER (ORDER BY MONETARY ASC) AS M_SCORE
        FROM CustomerStats
    )
    SELECT
        CUSTOMER_UNIQUE_ID,
        RECENCY_DAYS,
        FREQUENCY,
        MONETARY,
        R_SCORE,
        F_SCORE,
        M_SCORE,
        CONCAT(R_SCORE::STRING, F_SCORE::STRING, M_SCORE::STRING) AS RFM_SCORE,
        -- Segmentation Buckets
        CASE 
            WHEN R_SCORE >= 4 AND F_SCORE >= 4 AND M_SCORE >= 4 THEN 'Champions'
            WHEN R_SCORE >= 3 AND F_SCORE >= 3 AND M_SCORE >= 3 THEN 'Loyal Customers'
            WHEN R_SCORE >= 3 AND F_SCORE <= 2 AND M_SCORE >= 3 THEN 'Potential Loyalists'
            WHEN R_SCORE <= 2 AND F_SCORE >= 3 AND M_SCORE >= 3 THEN 'At Risk'
            WHEN R_SCORE <= 2 AND F_SCORE <= 2 AND M_SCORE >= 3 THEN 'Can\'t Lose Them'
            WHEN R_SCORE <= 2 AND F_SCORE <= 2 AND M_SCORE <= 2 THEN 'Lost Customers'
            ELSE 'Others / New'
        END AS SEGMENT
    FROM RFMScores;
    
    RETURN 'RFM Customer Segments refreshed successfully!';
END;
$$;

-- Master Stored Procedure to Refresh All Analytical Models
CREATE OR REPLACE PROCEDURE REFRESH_ALL_ANALYTICS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    CALL REFRESH_ANALYTICS_DATA();
    CALL CALCULATE_CLV();
    CALL REFRESH_RFM_SEGMENTS();
    RETURN 'All analytical aggregates, CLV scores, and RFM segments refreshed successfully!';
END;
$$;


-- ==========================================
-- 3. CDC STREAMS & AUTOMATION TASKS
-- ==========================================

-- Change Data Capture (CDC) Streams on orders and payments
CREATE OR REPLACE STREAM ORDER_STREAM ON TABLE FACT_ORDERS;
CREATE OR REPLACE STREAM PAYMENT_STREAM ON TABLE FACT_PAYMENTS;

-- Task to run Daily Data Refresh at 1:00 AM UTC
CREATE OR REPLACE TASK DAILY_DATA_REFRESH_TASK
    WAREHOUSE = ECOMMERCE_WH
    SCHEDULE = 'USING CRON 0 1 * * * UTC'
AS
    CALL REFRESH_ALL_ANALYTICS();

-- Resume the task to start the schedule
ALTER TASK DAILY_DATA_REFRESH_TASK RESUME;


-- ==========================================
-- 4. ROLE-BASED ACCESS CONTROL (RBAC)
-- ==========================================

-- Create database roles
CREATE ROLE IF NOT EXISTS ANALYST_ROLE;
CREATE ROLE IF NOT EXISTS MANAGER_ROLE;
CREATE ROLE IF NOT EXISTS ADMIN_ROLE;

-- Set Hierarchy (Analyst < Manager < Admin)
GRANT ROLE ANALYST_ROLE TO ROLE MANAGER_ROLE;
GRANT ROLE MANAGER_ROLE TO ROLE ADMIN_ROLE;

-- Grants for ANALYST_ROLE (Usage on DB/Schema, read on views only)
GRANT USAGE ON DATABASE ECOMMERCE_DB TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA ECOMMERCE_DB.ECOMMERCE_SCHEMA TO ROLE ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE ECOMMERCE_WH TO ROLE ANALYST_ROLE;
GRANT SELECT ON VIEW ECOMMERCE_DB.ECOMMERCE_SCHEMA.CUSTOMER_ANALYTICS_VIEW TO ROLE ANALYST_ROLE;
GRANT SELECT ON VIEW ECOMMERCE_DB.ECOMMERCE_SCHEMA.REVENUE_ANALYTICS_VIEW TO ROLE ANALYST_ROLE;
GRANT SELECT ON VIEW ECOMMERCE_DB.ECOMMERCE_SCHEMA.PRODUCT_ANALYTICS_VIEW TO ROLE ANALYST_ROLE;
GRANT SELECT ON VIEW ECOMMERCE_DB.ECOMMERCE_SCHEMA.SELLER_ANALYTICS_VIEW TO ROLE ANALYST_ROLE;
GRANT SELECT ON VIEW ECOMMERCE_DB.ECOMMERCE_SCHEMA.REVIEW_ANALYTICS_VIEW TO ROLE ANALYST_ROLE;
GRANT SELECT ON TABLE ECOMMERCE_DB.ECOMMERCE_SCHEMA.REPORT_DAILY_KPI TO ROLE ANALYST_ROLE;

-- Grants for MANAGER_ROLE (inherits Analyst, read base tables, execute stored procedure)
GRANT SELECT ON ALL TABLES IN SCHEMA ECOMMERCE_DB.ECOMMERCE_SCHEMA TO ROLE MANAGER_ROLE;
GRANT USAGE ON PROCEDURE ECOMMERCE_DB.ECOMMERCE_SCHEMA.REFRESH_ANALYTICS_DATA() TO ROLE MANAGER_ROLE;

-- Grants for ADMIN_ROLE (inherits Manager, full privileges on schema)
GRANT ALL PRIVILEGES ON SCHEMA ECOMMERCE_DB.ECOMMERCE_SCHEMA TO ROLE ADMIN_ROLE;
